services:
  - type: web
    name: job-tracker-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
    healthCheckPath: /health
